executable="${CDT_HOME}/cdt"

[alias]
initcs="moab init csharp"
initj="moab init java"
initgo="moab init java sdk/sdk-golang"
cproj = "!checkout-projects.sh \"$@\""
co="moab checkout"
exec="moab exec --threads 1"
git="moab exec --threads 1 git"
hooks="!install-hooks.sh"
jira="!add-jira-prefix.sh"
ide="moab ide"
rmoab="moab refresh"
st="moab status"

# workspace related
[alias.ws]
# example cdt ws cs team/proj
cs="!cdt-get-cs-workspace.sh \"$@\""
go="!cdt-get-go-workspace.sh \"$@\""
java="!cdt-get-java-workspace.sh \"$@\""
# you can add shortcuts for a specific projects, through override.toml
# example:
# [alias.get]
# main-project="!cdt ws cs team/super-duper-project

# shell integration
# completion for the current shell (detected through the SHELL variable)
# example cdt shell show
[alias.shell]
show="!cdt-completion.sh show"
install="!cdt-completion.sh install"
