executable="${CDT_HOME}/cdt"

[alias]
initcs="moab init csharp"
initj="moab init java"
initgo="moab init java sdk/sdk-golang"
cproj = "!checkout-projects.sh \"$@\""
co="moab checkout"
hooks="!install-hooks.sh"
jira="!add-jira-prefix.sh"
ide="moab ide"
rmoab="moab refresh"
st="moab status"

[alias.get]
# example cdt get cs team/proj
cs="!cdt-get-cs-proj.sh \"$@\""
java="!cdt-get-java-proj.sh \"$@\""
